# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

FB_APP_ID: "1476275892691389"
FB_SECRET: "a1b785a7b7440b712437e0a4d24cba8a"

GOOGLE_ID: "892400976178-7kc49mq13o76rs3an9s9lfekbmmcvfp9.apps.googleusercontent.com"
GOOGLE_SECRET: "EkoAnSGbDgF41pwOg6zJwz_H"
