production:
  adapter: postgresql
  encoding: unicode
  database: phykings_app_production
  pool: 5
  timeout: 5000
  username: jordan
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: phykings_app_development
  pool: 5
  timeout: 5000
  username: jordan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: phykings_app_test
  pool: 5
  timeout: 5000
  username: jordan
  password:
