development:
  adapter: postgresql
  encoding: unicode
  database: phykings_app_development
  pool: 5
  timeout: 5000
  username: aleksandar
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: phykings_app_test
  pool: 5
  timeout: 5000
  min_messages: WARNING
  username: aleksandar
  password:
